version: '3'

networks:
  public_chatbot_network:

services:

  db:
    hostname: db
    image: ankane/pgvector
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_DB=vectordb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - public_chatbot_network

  public-chatbot-be:
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - public_chatbot_network

  public-chatbot-fe:
    build:
      context: ./src/web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # volumes:
    #   - ./src/web:/app
      # - /app/src/web/node_modules
    # command: yarn dev
    networks:
      - public_chatbot_network
  
