config:
  data:
    ENV: prod
    CHANGE_CAUSE: init

replicas: 1

secret:
  stringData:
    OPENAI_API_KEY: 

image:
  nginx:
    repository: gitlab.paysera.net:5050/ai_rnd/app-public-chat/nginx
    tag: init
  node:
    repository: gitlab.paysera.net:5050/ai_rnd/app-public-chat/frontend
    tag: init
  python:
    repository: gitlab.paysera.net:5050/ai_rnd/app-public-chat/backend
    tag: init

resources:
  nginx:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 1Gi
      cpu: 1000m
  node:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 1Gi
      cpu: 1000m
  python:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 1Gi
      cpu: 1000m

service:
  enabled: true



